### ISSUE TITLE
Hello world project uses 100% CPU

### ISSUE THREAD

**Issue by geotre** [ftsf/nico#23]
Using Nico 0.2.6, Nim 1.2.2, a default hello world example project created using `nicoboot` uses 100% of one CPU core. Is this because the framerate is uncapped? I don't see any way of setting a target framerate in the API doc

**Comment by ftsf** [comment]
@geotre you can set the framerate with `fps(30)` or `fps(60)` for example, the default is `fps(60)`.
However I don't see the same behaviour, which OS are you running on and is this the web build or native SDL2 build?

This is what I see on windows 10 after doing a fresh `nicoboot tmp` `nimble runr`.
![image](https://user-images.githubusercontent.com/141492/85934481-50941800-b926-11ea-834f-a992cd2d71af.png)

It does seem excessive though, there is a commented out delay(0) in `nico.nim` https://github.com/ftsf/nico/blob/master/nico/backends/sdl2.nim#L655 which probably shouldn't be commented out
Please try uncommenting that line and recompiling and see if you see the behaviour you expect.

**Comment by geotre** [comment]
This is with the native SDL2 build on Ubuntu 18.04.

I can confirm that uncommenting the `delay(0)` does not fix the issue. Setting `fps(60)`, `fps(30)`, even `fps(1)` doesn't change the cpu usage

**Comment by geotre** [comment]
After profiling for a few seconds I can see that the `gameUpdate`, `gameDraw` procedures were called 7 times, but the `step` function was called 129,546 times in the same period. This is probably the cause of the issue. From a quick look at the code it seems like the sdl2 backend calls step in a constant loop with no delays, and I can't tell where the fps setting is handled in this

**Comment by ftsf** [comment]
@geotre I can reproduce the behaviour you see when running on Linux, I'll see what I can do.

**Comment by auxym** [comment]
Just wanted to chime in that I'm experiencing the same issue on linux. Let me know if there's anything I can do to help.

**Comment by auxym** [comment]
So I did some investigating. First, I noticed that the true framerate seems to be 2X whatever is set by `fps()`. Weird, but I couldn't figure out why. As to CPU usage:

## First the quick answer

Putting the `delay(0)` call inside `step`,  right after the `checkInput()` call, mostly fixes the problem. The reason is that  `flip` is limited by the frame rate (`fps` proc), and so `delay(0)` gets called only once per frame, but all the while we're hammering the cpu by continuously running `step` and polling for input with no delay. On my laptop, calling  `delay` after each `checkInput` reduces CPU usage to around 30%, which reasonable.

## More musings

In an ideal world, when we are done with the update and draw procs, we could put the process to sleep until we are are ready to frame the next frame. The problem is that we want to keep polling for inputs between frames, I assume, otherwise you might miss a quick button-mash that happened in between 2 frames. SDL allows getting input events asynchronously via `SDL_WaitEvent`. Perhaps this could be used instead of `PollEvent` in between frames? From my reading of the code, in any case, there is no event-polling going on while the user draw/update funcs run, so there would no change to the current situation, which is that input could be missed during the update/draw run time.

SDL does not allow polling/waiting for events outside the main thread (https://wiki.libsdl.org/SDL_PumpEvents). However, as a further improvement, perhaps one thing we could do is offload the user update/draw function execution to a second thread? That way we can use `SDL_WaitEventTimeout` to continue lazily handling events in-between two frames, while the game logic executes in parallel. The timeout is over when we are ready to present the frame, at this point, grab the pixel buffer from the second thread, present it to screen, then start a new iteration of update/draw in the worker thread while you handle input via `WaitEventTimeout` in the main thread.

Sorry for the rant, this is from a very quick reading of the nico code. If any of it makes sense, I can look into trying to piece together a quick POC. The `delay(0)` callsite fix is however a quick win, I think.

**Comment by ftsf** [comment]
I've pushed a potential fix by calling `delay(0)` after `step`. If you were experiencing the issue on Linux please let me know if this fixes it.

**Comment by opselo** [comment]
With the new fix ....

- In the gui example, consumption has dropped from 100% to 65%
- In the nicosynth tool from 100% to 45%
Tested on Debian 10_64_Plasma (old dual core 2 x 2.4)
Thanks !!
