### ISSUE TITLE
Add JS backend support and documentation for Event handling

### ISSUE THREAD

**Issue by avahe-kellenberger** [ftsf/nico#24]
Input seems to only be able to manually be checked, which results in missed inputs. It would be nice to have a callback system to have more reliable input.

**Comment by ftsf** [comment]
Hmm missing inputs shouldn't be happening, if so that's a bug, have you encountered this.
However inputs will be included in the next update.
There is an experimental undocumented API for handling events immediately.

https://github.com/ftsf/nico/blob/master/nico/backends/common.nim#L98

https://github.com/ftsf/nico/blob/master/nico.nim#L2767

```nim
addEventListener(proc(e: Event): bool =
  echo e.kind
)
```

**Comment by ftsf** [comment]
JS backend is now removed, using emscripten is now the way to build for web.
